@Host = http://localhost:5088

### LIST
GET {{Host}}/products/
Accept: application/json

### GET
GET {{Host}}/products/36d37e7f-2cf1-4397-86be-08cba6165697
Accept: application/json

### POST
POST {{Host}}/products/
Accept: application/json
Content-Type: application/json

{
    "name": "Product 3"
}

### PUT
PUT {{Host}}/products/36d37e7f-2cf1-4397-86be-08cba6165697
Accept: application/json
Content-Type: application/json

{
    "name": "Product 123"
}

###
DELETE {{Host}}/products/36d37e7f-2cf1-4397-86be-08cba6165697
Accept: application/json

###
