@Host = http://localhost:5088

GET {{Host}}/products/
Accept: application/json

###

GET {{Host}}/products/38fc522c-de9c-4500-ab77-0617f547e9c5/
Accept: application/json

###

POST {{Host}}/products/
Accept: application/json
Content-Type: application/json

{
    "name": "Product 3"
}

###

PUT {{Host}}/products/38fc522c-de9c-4500-ab77-0617f547e9c5/
Accept: application/json
Content-Type: application/json

{
    "name": "Product 123"
}

###

DELETE {{Host}}/products/8e01d5fd-3918-468b-a837-699fae0ba8ec/
Accept: application/json

###
